/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMyProfileRouteImport } from './routes/_authenticated/my-profile'
import { Route as AuthenticatedPendingApprovalsRouteImport } from './routes/_authenticated/pending-approvals'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents/$agentId'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents/new'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProfileRoute = AuthenticatedMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingApprovalsRoute =
  AuthenticatedPendingApprovalsRouteImport.update({
    id: '/pending-approvals',
    path: '/pending-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/my-profile': typeof AuthenticatedMyProfileRoute
  '/pending-approvals': typeof AuthenticatedPendingApprovalsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/my-profile': typeof AuthenticatedMyProfileRoute
  '/pending-approvals': typeof AuthenticatedPendingApprovalsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/my-profile': typeof AuthenticatedMyProfileRoute
  '/_authenticated/pending-approvals': typeof AuthenticatedPendingApprovalsRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/admins'
    | '/my-profile'
    | '/pending-approvals'
    | '/agents/$agentId'
    | '/agents/new'
    | '/agents/'
    | '/attendance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/admins'
    | '/my-profile'
    | '/pending-approvals'
    | '/agents/$agentId'
    | '/agents/new'
    | '/agents'
    | '/attendance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/admins'
    | '/_authenticated/my-profile'
    | '/_authenticated/pending-approvals'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/agents/new'
    | '/_authenticated/agents/'
    | '/_authenticated/attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-profile': {
      id: '/_authenticated/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AuthenticatedMyProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-approvals': {
      id: '/_authenticated/pending-approvals'
      path: '/pending-approvals'
      fullPath: '/pending-approvals'
      preLoaderRoute: typeof AuthenticatedPendingApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedMyProfileRoute: typeof AuthenticatedMyProfileRoute
  AuthenticatedPendingApprovalsRoute: typeof AuthenticatedPendingApprovalsRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedMyProfileRoute: AuthenticatedMyProfileRoute,
  AuthenticatedPendingApprovalsRoute: AuthenticatedPendingApprovalsRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
